Title only shown after question answered and feedback shown updates (re #682)
gowithfloat/adapt-question-feedback pull request #3
Opened 2018-04-02 16:42 UTC by Sauder91

2018-04-03 04:06 UTC, mediabounds requested changes

2018-04-03 04:06 UTC, mediabounds commented on js/adapt-question-feedback.js
> +            this.render();
@Sauder91 I don't think it is necessary to call render here--at line 8, a listener is set up to automatically re-render the component when feedback changes.

2018-04-03 04:06 UTC, mediabounds commented on templates/question-feedback.hbs
> +		{{#if feedback}}
@Sauder91 Can you fix the indentation here and at line 42?

2018-04-05 14:07 UTC, Sauder91 commented on js/adapt-question-feedback.js
> +            this.render();
I originally had it without adding this render call and it wasn't updating.  Maybe the change:feedback isn't being triggered except on the first update?

2018-04-05 15:01 UTC, mediabounds commented on js/adapt-question-feedback.js
> +            this.render();
Okay, let's keep this and then remove the change listener.

2018-04-05 19:11 UTC, closed without merging